import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { AnimatePresence } from "framer-motion";
import ProgressBar from "@badrap/bar-of-progress";
import Router from "next/router";

import "../styles/main.scss";

const progress = new ProgressBar({
  size: 4,
  color: "#C98C48",
  className: "z-50",
  delay: 100,
});

Router.events.on("routeChangeStart", progress.start);
Router.events.on("routeChangeComplete", progress.finish);
Router.events.on("routeChangeError", progress.finish);

function MyApp({ Component, pageProps }) {
  return (
    <div className="wrapper">
      <Head>
        <title>TofanConsult</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AnimatePresence exitBeforeEnter initial={true}>
        <Component {...pageProps} />
      </AnimatePresence>
      <Footer />
    </div>
  );
}

export default MyApp;
